### ISSUE TITLE
Leaflet 1.0.3 and touchscreen

### ISSUE THREAD

**Issue by manukieli** [SINTEF-9012/Leaflet.MapPaint#3]
I'm using this very usefull plugin and work fine with leaflet version 0.7.x.
Recently i'm update leafltet to 1.0.3 version. With the mouse it work fine. But with a touchscreen, when then event "**_onTouchMove**" it's fire, the "**_onTouchEnd**" event is fired after and i can't draw.
Can someone help me.

**Comment by manukieli** [comment]
I've resolve it.
See this link: https://github.com/Leaflet/Leaflet/issues/5323

**Comment by fungiboletus** [comment]
Do you think `.leaflet-container { touch-action: none; }` should be added in Leaflet or in this library ?

**Comment by manukieli** [comment]
I've add it to a CSS file that I use like custom css code.
